### ISSUE TITLE
Typo in Display name OCT 

### ISSUE THREAD

**Issue by chgessner** [gematik/ePA-XDS-Document#8]
https://github.com/gematik/ePA-XDS-Document/blob/4ff466a95a7a99dce12f27c7f6b0a759450d0363/src/implementation_guides/ig-medical-image.json#L99

Sollte heißen "Optical Coherence Tomography", also ohne "th".

**Comment by michaelonken** [comment]
Fixed upstream, will be available on GitHub soon.
