### ISSUE TITLE
Typo in Display name "MR"

### ISSUE THREAD

**Issue by chgessner** [gematik/ePA-XDS-Document#9]
https://github.com/gematik/ePA-XDS-Document/blob/4ff466a95a7a99dce12f27c7f6b0a759450d0363/src/implementation_guides/ig-medical-image.json#L89

Überflüssiges "MR" am Ende.
Sollte heißen "Magnetic Resonance", also ohne MR am Ende.

**Comment by michaelonken** [comment]
Fixed upstream, will be available on GitHub soon.
